### ISSUE TITLE
Data Conversion Error in CSV format 

### ISSUE THREAD

**Issue by akhanna-mdsol** [wakatime/wakadump#3]
Hi 

I installed this tool and trying to convert my json to csv. But since it's a nested JSON. I only get this back in the CSV file. Is this expected?

Date,Total Logged Seconds
09-22-2015,0
09-23-2015,17151
09-24-2015,6016
09-25-2015,9533
09-26-2015,4521
09-27-2015,0
09-28-2015,14747
09-29-2015,25890
09-30-2015,22254
10-01-2015,43
10-02-2015,9113

**Comment by alanhamlett** [comment]
Yes, that's the list of each day and the total seconds you logged in your text editor for that day. We can add more info to the CSV like time logged per file, project, editor, os, and language if needed:

https://github.com/wakatime/wakadump/blob/master/wakadump/formats/csv.py

**Comment by akhanna-mdsol** [comment]
Can I please get other fields in CSV format?

**Comment by alanhamlett** [comment]
Added in v2.0.3.
